use apt-get instead of apt

diff --git a/bin/af b/bin/af
--- a/bin/af
+++ b/bin/af
@@ -8,9 +8,9 @@ ACTION=
 CLEANUP=
 UPDATE=
 
-if ! which apt 2>/dev/null >/dev/null; then
+if ! which apt-get 2>/dev/null >/dev/null; then
 	if [[ ! "$@" =~ -r ]]; then
-		echo "Command 'apt' not found."
+		echo "Command 'apt-get' not found."
 		exit 1
 	fi
 fi
@@ -22,7 +22,7 @@ function printhelp {
 
 $sname - the 'af' script
 
-A wrapper for \`apt\` to manage packages more lazily (from a typing perspective!)
+A wrapper for \`apt-get\` and \`apt-cache\` to manage packages more lazily (from a typing perspective!)
 
 The tool uses sudo to run actions that require root.
 
@@ -172,24 +172,24 @@ while [[ -n "$@" ]]; do
 done
 
 if [[ $UPDATE = yes ]]; then
-	sudo apt update
+	sudo apt-get update
 fi
 
 
 if [[ $ACTION = install ]]; then
-	[[ -n "$PACKAGELIST" ]] && sudo apt install $PACKAGELIST $ASSUMEYN
+	[[ -n "$PACKAGELIST" ]] && sudo apt-get install --show-progress $PACKAGELIST $ASSUMEYN
 
 elif [[ $ACTION = remove ]]; then
-	[[ -n "$PACKAGELIST" ]] && sudo apt remove $PACKAGELIST $ASSUMEYN
+	[[ -n "$PACKAGELIST" ]] && sudo apt-get remove --show-progress $PACKAGELIST $ASSUMEYN
 
 elif [[ $ACTION = purge ]]; then
 	[[ -n "$PACKAGELIST" ]] && sudo apt-get purge $PACKAGELIST $ASSUMEYN
 
 elif [[ $ACTION = upgrade ]]; then
 	if [[ -n "$PACKAGELIST" ]] && [[ "$ASSUMEYN" != '-y' ]]; then
-		sudo apt install $PACKAGELIST $ASSUMEYN
+		sudo apt-get install --show-progress $PACKAGELIST $ASSUMEYN
 	else
-		sudo apt upgrade $ASSUMEYN
+		sudo apt-get dist-upgrade --show-progress $ASSUMEYN
 	fi
 
 elif [[ $ACTION = uprelease ]]; then
