rebuild with bash-libs 1.4.1

diff --git a/bin/paf b/bin/paf
--- a/bin/paf
+++ b/bin/paf
@@ -77,14 +77,19 @@ PAF_configdir="/etc/alpacka"
 ###/doc
 
 
-##bash-libs: autohelp.sh @ f6496eca (1.1.4)
 
-### autohelp:print [ SECTION [FILE] ] Usage:bbuild
+##bash-libs: autohelp.sh @ bf310b32 (1.4.1)
+
+### Autohelp Usage:bbuild
+#
+# Autohelp provides some simple facilities for defining help as comments in your code.
+# It provides several functions for printing specially formatted comment sections.
+#
 # Write your help as documentation comments in your script
 #
-# If you need to output the help from your script, or a file, call the
+# To output a named section from your script, or a file, call the
 # `autohelp:print` function and it will print the help documentation
-# in the current script to stdout
+# in the current script, or specified file, to stdout
 #
 # A help comment looks like this:
 #
@@ -97,7 +102,11 @@ PAF_configdir="/etc/alpacka"
 #    #
 #    ###/doc
 #
-# You can set a different help section by specifying a subsection
+# It can then be printed from the same script by simply calling
+#
+#   autohelp:print
+#
+# You can print a different section by specifying a different name
 #
 # 	autohelp:print section2
 #
@@ -107,43 +116,112 @@ PAF_configdir="/etc/alpacka"
 # 	# <some content>
 # 	###/doc
 #
-# You can set a different comment character by setting the 'HELPCHAR' environment variable:
+# You can set a different comment character by setting the 'HELPCHAR' environment variable.
+# Typically, you might want to print comments you set in a INI config file, for example
 #
-# 	HELPCHAR=%
+# 	HELPCHAR=";" autohelp:print help config-file.ini
+# 
+# Which would then find comments defined like this in `config-file.ini`:
 #
+#   ;;; Main config Usage:help
+#   ; Help comments in a config file
+#   ; may start with a different comment character
+#   ;;;/doc
+#
+#
+#
+# Example usage in a multi-function script:
+#
+#   #!/bin/bash
+#
+#   ### Main help Usage:help
+#   # The main help
+#   ###/doc
+#
+#   ### Feature One Usage:feature_1
+#   # Help text for the first feature
+#   ###/doc
+#
+#   feature1() {
+#       autohelp:check_section feature_1 "$@"
+#       echo "Feature I"
+#   }
+#
+#   ### Feature Two Usage:feature_2
+#   # Help text for the second feature
+#   ###/doc
+#
+#   feature2() {
+#       autohelp:check_section feature_2 "$@"
+#       echo "Feature II"
+#   }
+#
+#   main() {
+#       if [[ -z "$*" ]]; then
+#           ### No command specified Usage:no-command
+#           #No command specified. Try running with `--help`
+#           ###/doc
+#
+#           autohelp:print no-command
+#           exit 1
+#       fi
+#
+#       case "$1" in
+#       feature1|feature2)
+#           "$1" "$@"            # Pass the global script arguments through
+#           ;;
+#       *)
+#           autohelp:check "$@"  # Check if main help was asked for, if so, exits
+#
+#           # Main help not requested, return error
+#           echo "Unknown feature"
+#           exit 1
+#           ;;
+#       esac
+#   }
+#
+#   main "$@"
+#
+###/doc
+
+### autohelp:print [ SECTION [FILE] ] Usage:bbuild
+# Print the specified section, in the specified file.
+#
+# If no file is specified, prints for current script file.
+# If no section is specified, defaults to "help"
 ###/doc
 
 HELPCHAR='#'
 
-function autohelp:print {
-    local SECTION_STRING="${1:-}"; shift || :
-    local TARGETFILE="${1:-}"; shift || :
-    [[ -n "$SECTION_STRING" ]] || SECTION_STRING=help
-    [[ -n "$TARGETFILE" ]] || TARGETFILE="$0"
+autohelp:print() {
+    local input_line
+    local section_string="${1:-}"; shift || :
+    local target_file="${1:-}"; shift || :
+    [[ -n "$section_string" ]] || section_string=help
+    [[ -n "$target_file" ]] || target_file="$0"
 
-        echo -e "\n$(basename "$TARGETFILE")\n===\n"
-        local SECSTART='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s+(.+?)\s+Usage:'"$SECTION_STRING"'\s*$'
-        local SECEND='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s*/doc\s*$'
-        local insec=false
+    #echo -e "\n$(basename "$target_file")\n===\n"
+    local sec_start='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s+(.+?)\s+Usage:'"$section_string"'\s*$'
+    local sec_end='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s*/doc\s*$'
+    local in_section=false
 
-        while read secline; do
-                if [[ "$secline" =~ $SECSTART ]]; then
-                        insec=true
-                        echo -e "\n${BASH_REMATCH[1]}\n---\n"
+    while read input_line; do
+        if [[ "$input_line" =~ $sec_start ]]; then
+            in_section=true
+            echo -e "\n${BASH_REMATCH[1]}\n======="
 
-                elif [[ "$insec" = true ]]; then
-                        if [[ "$secline" =~ $SECEND ]]; then
-                                insec=false
-                        else
-                echo "$secline" | sed -r "s/^\s*$HELPCHAR//g"
-                        fi
-                fi
-        done < "$TARGETFILE"
-
-        if [[ "$insec" = true ]]; then
-                echo "WARNING: Non-terminated help block." 1>&2
+        elif [[ "$in_section" = true ]]; then
+            if [[ "$input_line" =~ $sec_end ]]; then
+                in_section=false
+            else
+                echo "$input_line" | sed -r "s/^\s*$HELPCHAR/ /;s/^  (\S)/\1/"
+            fi
         fi
-    echo ""
+    done < "$target_file"
+
+    if [[ "$in_section" = true ]]; then
+            out:fail "Non-terminated help block."
+    fi
 }
 
 ### autohelp:paged Usage:bbuild
@@ -151,44 +229,37 @@ function autohelp:print {
 # Display the help in the pager defined in the PAGER environment variable
 #
 ###/doc
-function autohelp:paged {
+autohelp:paged() {
     : ${PAGER=less}
     autohelp:print "$@" | $PAGER
 }
 
-### autohelp:check Usage:bbuild
+### autohelp:check ARGS ... Usage:bbuild
 #
-# Automatically print help and exit if "--help" is detected in arguments
-#
-# Example use:
-#
-#    #!/bin/bash
-#
-#    ### Some help Usage:help
-#    #
-#    # Some help text
-#    #
-#    ###/doc
-#
-#    #%include autohelp.sh
-#
-#    main() {
-#        autohelp:check "$@"
-#
-#        # now add your code
-#    }
-#
-#    main "$@"
+# Automatically print "help" sections and exit, if "--help" is detected in arguments
 #
 ###/doc
 autohelp:check() {
-    if [[ "$*" =~ --help ]]; then
-        cols="$(tput cols)"
-        autohelp:print | fold -w "$cols" -s || autohelp:print
-        exit 0
-    fi
+    autohelp:check_section "help" "$@"
 }
-##bash-libs: bincheck.sh @ f6496eca (1.1.4)
+
+### autohelp:check_section SECTION ARGS ... Usage:bbuild
+# Automatically print documentation for named section and exit, if "--help" is detected in arguments
+#
+###/doc
+autohelp:check_section() {
+    local section arg
+    section="${1:-}"; shift || out:fail "No help section specified"
+
+    for arg in "$@"; do
+        if [[ "$arg" =~ --help ]]; then
+            cols="$(tput cols)"
+            autohelp:print "$section" | fold -w "$cols" -s || autohelp:print "$section"
+            exit 0
+        fi
+    done
+}
+##bash-libs: bincheck.sh @ bf310b32 (1.4.1)
 
 ### bincheck:get COMMANDS ... Usage:bbuild
 #
@@ -260,9 +331,7 @@ bincheck:path() {
     
     } || echo "$binname"
 }
-##bash-libs: args.sh @ f6496eca (1.1.4)
-
-##bash-libs: patterns.sh @ f6496eca (1.1.4)
+##bash-libs: patterns.sh @ bf310b32 (1.4.1)
 
 ### Useful patterns Usage:bbuild
 #
@@ -286,6 +355,8 @@ export PAT_num='^[0-9]+$'
 export PAT_cvar='^[a-zA-Z_][a-zA-Z0-9_]*$'
 export PAT_filename='^[a-zA-Z0-9_.-]$'
 export PAT_email="$PAT_filename@$PAT_filename.$PAT_cvar"
+
+##bash-libs: args.sh @ bf310b32 (1.4.1)
 
 ### args Usage:bbuild
 #
@@ -316,7 +387,7 @@ export PAT_email="$PAT_filename@$PAT_filename.$PAT_cvar"
 #
 ###/doc
 
-function args:get {
+args:get() {
     local seek="$1"; shift || :
 
     if [[ "$seek" =~ $PAT_num ]]; then
@@ -340,7 +411,7 @@ function args:get {
     fi
 }
 
-function args:get_short {
+args:get_short() {
     local token="$1"; shift || :
     while [[ -n "$*" ]]; do
         local item="$1"; shift || :
@@ -353,7 +424,7 @@ function args:get_short {
     return 1
 }
 
-function args:get_long {
+args:get_long() {
     local token="$1"; shift || :
     local tokenpat="^$token=(.*)$"
 
@@ -386,7 +457,7 @@ function args:get_long {
 #
 ###/doc
 
-function args:has {
+args:has() {
     local token="$1"; shift || :
     for item in "$@"; do
         if [[ "$token" = "$item" ]]; then
@@ -415,7 +486,7 @@ function args:has {
 #
 ###/doc
 
-function args:after {
+args:after() {
     local token="$1"; shift || :
     
     local current_token="$1"; shift || :
@@ -425,7 +496,91 @@ function args:after {
 
     RETARR_ARGSAFTER=("$@")
 }
-##bash-libs: runmain.sh @ f6496eca (1.1.4)
+
+### args:use ARGNAMES ... -- ARGVALUES ... Usage:bbuild
+# 
+# Consume arguments into named global variables.
+#
+# If not enough argument values are found, the first named variable that failed to be assigned is printed as error
+#
+# ARGNAMES prefixed with '?' do not trigger an error
+#
+# Example:
+#
+#   #%include out.sh
+#   #%include args.sh
+#
+#   get_parameters() {
+#       . <(args:use INFILE OUTFILE ?comment -- "$@")
+#
+#       [[ -f "$INFILE" ]]  || out:fail "Input file '$INFILE' does not exist"
+#       [[ -f "$OUTFILE" ]] || out:fail "Output file '$OUTFILE' does not exist"
+#
+#       [[ -z "$comment" ]] || echo "Note: $comment"
+#   }
+#
+#   main() {
+#       get_parameters "$@"
+#
+#       echo "$INFILE will be converted to $OUTFILE"
+#   }
+#
+#   main "$@"
+#
+###/doc
+args:use() {
+    local argname arglist undef_f
+    arglist=(:)
+    for argname in "$@"; do
+        [[ "$argname" != -- ]] || break
+        [[ "$argname" =~ ^\??[0-9a-zA-Z_]+$ ]] || out:fail "Internal: Not a valid argument name '$argname'"
+
+        arglist+=("$argname")
+    done
+
+    for argname in "${arglist[@]:1}"; do
+        if [[ "$argname" =~ ^\? ]]; then
+            argname="${argname:1}"
+            undef_f=":"
+        else
+            undef_f="out:fail \"Internal : could not get '$argname'\""
+        fi
+
+        echo "$ARGSLIB_scope $argname=\"\${1:-}\"; shift || $undef_f"
+    done
+}
+
+
+### args:use:local ARGNAMES ... -- ARGVALUES ... Usage:bbuild
+# 
+# Consume arguments into named variables. You need to use process subtitution and sourcing
+#   to call the function, so that it affects the scope in your function.
+#
+# If not enough argument values are found, the named variable that failed to be assigned is printed as error
+#
+# Example:
+#
+#   #%include out.sh
+#   #%include args.sh
+#
+#   person() {
+#       . <(args:use:local name email -- "$@")
+#
+#       echo "$name <$email>"
+#
+#       # $1 and $2 have been consumed into $name and $email
+#       # The rest remains available in $* :
+#       
+#       echo "Additional notes: $*"
+#   }
+#
+#   person "Jo Smith" "jsmith@exam0ple.com" Some details
+#
+###/doc
+args:use:local() {
+    ARGSLIB_scope=local args:use "$@"
+}
+##bash-libs: runmain.sh @ bf310b32 (1.4.1)
 
 ### runmain SCRIPTNAME FUNCTION [ARGUMENTS ...] Usage:bbuild
 #
@@ -460,39 +615,7 @@ function runmain {
         "$funcall" "$@"
     fi
 }
-##bash-libs: out.sh @ f6496eca (1.1.4)
-
-##bash-libs: colours.sh @ f6496eca (1.1.4)
-
-### Colours for bash Usage:bbuild
-# A series of colour flags for use in outputs.
-#
-# Example:
-# 	
-# 	echo -e "${CRED}Some red text ${CBBLU} some blue text $CDEF some text in the terminal's default colour")
-#
-# Requires processing of escape characters.
-#
-# Colours available:
-#
-# CRED, CBRED, HLRED -- red, bold red, highlight red
-# CGRN, CBGRN, HLGRN -- green, bold green, highlight green
-# CYEL, CBYEL, HLYEL -- yellow, bold yellow, highlight yellow
-# CBLU, CBBLU, HLBLU -- blue, bold blue, highlight blue
-# CPUR, CBPUR, HLPUR -- purple, bold purple, highlight purple
-# CTEA, CBTEA, HLTEA -- teal, bold teal, highlight teal
-#
-# CDEF -- switches to the terminal default
-# CUNL -- add underline
-#
-# Note that highlight and underline must be applied or re-applied after specifying a colour.
-#
-# If the session is detected as being in a pipe, colours will be turned off.
-#   You can override this by calling `colours:check --color=always` at the start of your script
-#
-###/doc
-
-##bash-libs: tty.sh @ f6496eca (1.1.4)
+##bash-libs: tty.sh @ bf310b32 (1.4.1)
 
 tty:is_ssh() {
     [[ -n "$SSH_TTY" ]] || [[ -n "$SSH_CLIENT" ]] || [[ "$SSH_CONNECTION" ]]
@@ -502,10 +625,65 @@ tty:is_pipe() {
     [[ ! -t 1 ]]
 }
 
-### colours:check ARGS Usage:bbuild
+##bash-libs: colours.sh @ bf310b32 (1.4.1)
+
+### Colours for terminal Usage:bbuild
+# A series of shorthand colour flags for use in outputs, and functions to set your own flags.
+#
+# Not all terminals support all colours or modifiers.
+#
+# Example:
+# 	
+# 	echo "${CRED}Some red text ${CBBLU} some blue text. $CDEF Some text in the terminal's default colour")
+#
+# Preconfigured colours available:
+#
+# CRED, CBRED, HLRED -- red, bright red, highlight red
+# CGRN, CBGRN, HLGRN -- green, bright green, highlight green
+# CYEL, CBYEL, HLYEL -- yellow, bright yellow, highlight yellow
+# CBLU, CBBLU, HLBLU -- blue, bright blue, highlight blue
+# CPUR, CBPUR, HLPUR -- purple, bright purple, highlight purple
+# CTEA, CBTEA, HLTEA -- teal, bright teal, highlight teal
+# CBLA, CBBLA, HLBLA -- black, bright red, highlight red
+# CWHI, CBWHI, HLWHI -- white, bright red, highlight red
+#
+# Modifiers available:
+#
+# CBON - activate bright
+# CDON - activate dim
+# ULON - activate underline
+# RVON - activate reverse (switch foreground and background)
+# SKON - activate strikethrough
+# 
+# Resets available:
+#
+# CNORM -- turn off bright or dim, without affecting other modifiers
+# ULOFF -- turn off highlighting
+# RVOFF -- turn off inverse
+# SKOFF -- turn off strikethrough
+# HLOFF -- turn off highlight
+#
+# CDEF -- turn off all colours and modifiers(switches to the terminal default)
+#
+# Note that highlight and underline must be applied or re-applied after specifying a colour.
+#
+# If the session is detected as being in a pipe, colours will be turned off.
+#   You can override this by calling `colours:check --color=always` at the start of your script
+#
+###/doc
+
+### colours:check ARGS ... Usage:bbuild
 #
 # Check the args to see if there's a `--color=always` or `--color=never`
 #   and reload the colours appropriately
+#
+#   main() {
+#       colours:check "$@"
+#
+#       echo "${CGRN}Green only in tty or if --colours=always !${CDEF}"
+#   }
+#
+#   main "$@"
 #
 ###/doc
 colours:check() {
@@ -519,6 +697,74 @@ colours:check() {
     return 0
 }
 
+### colours:set CODE Usage:bbuild
+# Set an explicit colour code - e.g.
+#
+#   echo "$(colours:set "33;2")Dim yellow text${CDEF}"
+#
+# See SGR Colours definitions
+#   <https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters>
+###/doc
+colours:set() {
+    # We use `echo -e` here rather than directly embedding a binary character
+    if [[ "$COLOURS_ON" = false ]]; then
+        return 0
+    else
+        echo -e "\033[${1}m"
+    fi
+}
+
+colours:define() {
+
+    # Shorthand colours
+
+    export CBLA="$(colours:set "30")"
+    export CRED="$(colours:set "31")"
+    export CGRN="$(colours:set "32")"
+    export CYEL="$(colours:set "33")"
+    export CBLU="$(colours:set "34")"
+    export CPUR="$(colours:set "35")"
+    export CTEA="$(colours:set "36")"
+    export CWHI="$(colours:set "37")"
+
+    export CBBLA="$(colours:set "1;30")"
+    export CBRED="$(colours:set "1;31")"
+    export CBGRN="$(colours:set "1;32")"
+    export CBYEL="$(colours:set "1;33")"
+    export CBBLU="$(colours:set "1;34")"
+    export CBPUR="$(colours:set "1;35")"
+    export CBTEA="$(colours:set "1;36")"
+    export CBWHI="$(colours:set "1;37")"
+
+    export HLBLA="$(colours:set "40")"
+    export HLRED="$(colours:set "41")"
+    export HLGRN="$(colours:set "42")"
+    export HLYEL="$(colours:set "43")"
+    export HLBLU="$(colours:set "44")"
+    export HLPUR="$(colours:set "45")"
+    export HLTEA="$(colours:set "46")"
+    export HLWHI="$(colours:set "47")"
+
+    # Modifiers
+    
+    export CBON="$(colours:set "1")"
+    export CDON="$(colours:set "2")"
+    export ULON="$(colours:set "4")"
+    export RVON="$(colours:set "7")"
+    export SKON="$(colours:set "9")"
+
+    # Resets
+
+    export CBNRM="$(colours:set "22")"
+    export HLOFF="$(colours:set "49")"
+    export ULOFF="$(colours:set "24")"
+    export RVOFF="$(colours:set "27")"
+    export SKOFF="$(colours:set "29")"
+
+    export CDEF="$(colours:set "0")"
+
+}
+
 colours:auto() {
     if tty:is_pipe ; then
         COLOURS_ON=false
@@ -530,61 +776,9 @@ colours:auto() {
     return 0
 }
 
-colours:define() {
-    if [[ "$COLOURS_ON" = false ]]; then
-
-        export CRED=''
-        export CGRN=''
-        export CYEL=''
-        export CBLU=''
-        export CPUR=''
-        export CTEA=''
-
-        export CBRED=''
-        export CBGRN=''
-        export CBYEL=''
-        export CBBLU=''
-        export CBPUR=''
-        export CBTEA=''
-
-        export HLRED=''
-        export HLGRN=''
-        export HLYEL=''
-        export HLBLU=''
-        export HLPUR=''
-        export HLTEA=''
-
-        export CDEF=''
-
-    else
-
-        export CRED=$(echo -e "\033[0;31m")
-        export CGRN=$(echo -e "\033[0;32m")
-        export CYEL=$(echo -e "\033[0;33m")
-        export CBLU=$(echo -e "\033[0;34m")
-        export CPUR=$(echo -e "\033[0;35m")
-        export CTEA=$(echo -e "\033[0;36m")
-
-        export CBRED=$(echo -e "\033[1;31m")
-        export CBGRN=$(echo -e "\033[1;32m")
-        export CBYEL=$(echo -e "\033[1;33m")
-        export CBBLU=$(echo -e "\033[1;34m")
-        export CBPUR=$(echo -e "\033[1;35m")
-        export CBTEA=$(echo -e "\033[1;36m")
-
-        export HLRED=$(echo -e "\033[41m")
-        export HLGRN=$(echo -e "\033[42m")
-        export HLYEL=$(echo -e "\033[43m")
-        export HLBLU=$(echo -e "\033[44m")
-        export HLPUR=$(echo -e "\033[45m")
-        export HLTEA=$(echo -e "\033[46m")
-
-        export CDEF=$(echo -e "\033[0m")
-
-    fi
-}
-
 colours:auto
+
+##bash-libs: out.sh @ bf310b32 (1.4.1)
 
 ### Console output handlers Usage:bbuild
 #
@@ -671,7 +865,7 @@ function out:fail {
 function out:error {
     echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
 }
-##bash-libs: readkv.sh @ f6496eca (1.1.4)
+##bash-libs: readkv.sh @ bf310b32 (1.4.1)
 
 ### Key Value Pair Reader Usage:bbuild
 #
@@ -698,7 +892,7 @@ function readkv {
         thedefault="$1"; shift || :
     fi
 
-    local res="$(readkv:meaningful_data "$thefile"|egrep "^$thekey"'\s*='|sed -r "s/^$thekey"'\s*=\s*//')"
+    local res="$(readkv:meaningful_data "$thefile"|grep -E "^$thekey"'\s*='|sed -r "s/^$thekey"'\s*=\s*//')"
     if [[ -z "$res" ]]; then
         echo "${thedefault:-}"
     else
@@ -727,7 +921,7 @@ function readkv:require {
     readkv "$@"
 }
 
-### readkv:moeaningful_data FILE Usage:bbuild
+### readkv:meaningful_data FILE Usage:bbuild
 # Dump the file contents, stripping meaningless data (empty lines and comment lines)
 ###/doc
 readkv:meaningful_data() {
@@ -754,8 +948,8 @@ readkv:meaningful_data() {
 #
 ###/doc
 
-##bash-libs: isroot.sh @ f6496eca (1.1.4)
 
+##bash-libs: isroot.sh @ bf310b32 (1.4.1)
 
 ### isroot Usage:bbuild
 # Test for root access
