Display warnings ahead of executing steps

diff --git a/bin/paf b/bin/paf
--- a/bin/paf
+++ b/bin/paf
@@ -791,16 +791,21 @@ PAF_warningdir="$PAF_configdir/warnings"
 
 paf:warn() {
     local err=0
-    local sleepsec="${PAF_warning_sleep:-5}"
     [[ "$sleepsec" =~ ^[0-9]+$ ]] || out:fail "Warning sleep duration is not an int: $sleepsec"
 
     if paf:warn:display "${1:-}"; then
-        out:info "Press Ctrl+C within  $sleepsec seconds to abort, or Enter to continue ..."
+        paf:warn:grace-wait || out:fail "Error while waiting to continue ..."
+    fi
+}
 
-        read -t $sleepsec || err="$?"
-        if [[ "$err" = 0 ]] || [[ "$err" -ge 128 ]]; then
-            return 0
-        fi
+paf:warn:grace-wait() {
+    local sleepsec="${PAF_warning_sleep:-5}"
+
+    out:info "Press Ctrl+C within  $sleepsec seconds to abort, or Enter to continue ..."
+
+    read -t $sleepsec || err="$?"
+    if [[ "$err" = 0 ]] || [[ "$err" -ge 128 ]]; then
+        return 0
     fi
 }
 
@@ -824,12 +829,14 @@ paf:warn:display() {
     local warnfile
     warnfile="$PAF_warningdir/${1}.txt"
 
-    paf:warn:is-set "$warnfile" || return 1
+    paf:warn:is-set "$warnfile" || return 0 # not an error - if not set, ignore step
 
     echo -n "$CBYEL" >&2
     cat "$warnfile"
     echo
     echo -n "$CDEF" >&2
+
+    PAF_warned=true
 
     return 0
 }
@@ -854,10 +861,10 @@ paf:warn:write() {
     if [[ "$PAF_warnmessage" = "." ]]; then
         echo -n > "$PAF_warnpath"
     else
-        echo -n "$PAF_warntype message: ${PAF_warnmessage}" > "$PAF_warnpath"
+        echo -n "<$PAF_warntype>: ${PAF_warnmessage}" > "$PAF_warnpath"
     fi
 
-    out:info "Warning wwritten to $PAF_warnpath"
+    out:info "Warning written to $PAF_warnpath"
 }
 
 paf:warn:warn-set() {
@@ -903,8 +910,6 @@ paf:main() {
     paf:run_activity update
 
     if [[ -n "${PAF_action:-}" ]]; then
-        paf:warn "$PAF_action"
-
         # We pass "$@" in case it is needed
         #  but most actions just access ${PAF_packages[@]} directly
         "$PAF_pm:$PAF_action" "$@"
@@ -971,7 +976,6 @@ paf:add_activity() {
 paf:run_activity() {
     local activity="$1"
     if [[ "${PAF_activities[*]:-}" =~ "$activity" ]]; then
-        paf:warn "$activity"
         "$PAF_pm:$activity"
     fi
 }
@@ -1017,6 +1021,24 @@ paf:parse_arguments() {
     # blat the holders
     PAF_activities=("${PAF_activities[@]:1}")
     PAF_packages=("${PAF_packages[@]:1}")
+
+    # Issue all warnings in bulk as soon as we know our activities
+    #   so user sees them early
+    paf:issue_warnings "${PAF_activities[@]:-}" "$PAF_action"
+}
+
+paf:issue_warnings() {
+    local warning
+    PAF_warned=false
+
+    for warning in "$@"; do
+        [[ -n "$warning" ]] || continue
+        paf:warn:display "$warning"
+    done
+
+    if [[ "$PAF_warned" = true ]]; then
+        paf:warn:grace-wait
+    fi
 }
 
 ppa:add() {
